name: Run Workflow Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Schedule to run every 3 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify Node.js version 16
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        pip install requests
        pip install beautifulsoup4
        pip install twilio
    - name: Run Script
      run: |
        python fetch_changes.py ${{ secrets.PHONE_NUMBER_1 }} ${{ secrets.PHONE_NUMBER_2 }} ${{ secrets.ACCOUNT_SID }} ${{ secrets.AUTH_TOKEN }}
  
        git config --global user.email "denizj2828@gmail.com"
        git config --global user.name "Deniz-Jasa"
        git add previous_readme_hash.txt
        git commit -m "Update hash file via GitHub Actions"
        git push
