name: Run Fetch Script Every 3 Hours

on:
  schedule:
    - cron: '0 */3 * * *'  # Schedule to run every 3 hours

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run Fetch Script
      run: python fetch_script.py  # Replace with the name of your Python script
      env:
        PHONE_NUMBER_1: ${{ secrets.PHONE_NUMBER_1 }}
        PHONE_NUMBER_2: ${{ secrets.PHONE_NUMBER_2 }}
