name: Run Workflow Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Schedule to run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run Script
      run: python your_script.py  # Replace with the name of your Python script
